CREATE TABLE user_identity (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    external_subject VARCHAR(255) NOT NULL UNIQUE,
    email VARCHAR(255),
    created_at TIMESTAMP WITH TIME ZONE
);

CREATE TABLE monitor (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    owner_id BIGINT,
    name VARCHAR(255) NOT NULL,
    url VARCHAR(255) NOT NULL,
    method VARCHAR(20) NOT NULL,
    expected_status_code INTEGER NOT NULL CHECK (expected_status_code >= 100 AND expected_status_code <= 599),
    interval_minutes INTEGER NOT NULL CHECK (interval_minutes >= 1),
    timeout_seconds INTEGER NOT NULL CHECK (timeout_seconds >= 1),
    expected_keyword VARCHAR(255),
    failure_threshold INTEGER NOT NULL CHECK (failure_threshold >= 1 AND failure_threshold <= 10),
    consecutive_failures INTEGER NOT NULL CHECK (consecutive_failures >= 0),
    active BOOLEAN NOT NULL,
    status VARCHAR(20),
    created_at TIMESTAMP WITH TIME ZONE,
    last_checked_at TIMESTAMP WITH TIME ZONE,
    CONSTRAINT fk_monitor_owner FOREIGN KEY (owner_id) REFERENCES user_identity(id)
);

CREATE TABLE monitor_request_headers (
    monitor_id BIGINT NOT NULL,
    header_name VARCHAR(255) NOT NULL,
    header_value VARCHAR(255),
    PRIMARY KEY (monitor_id, header_name),
    CONSTRAINT fk_monitor_request_headers_monitor FOREIGN KEY (monitor_id) REFERENCES monitor(id)
);

CREATE TABLE check_result (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    monitor_id BIGINT,
    checked_at TIMESTAMP WITH TIME ZONE,
    status_code INTEGER,
    response_time_ms BIGINT NOT NULL,
    status VARCHAR(20),
    incident_transition VARCHAR(30),
    incident_reason VARCHAR(255),
    error_message VARCHAR(255),
    CONSTRAINT fk_check_result_monitor FOREIGN KEY (monitor_id) REFERENCES monitor(id)
);

CREATE TABLE incident (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    monitor_id BIGINT,
    opened_by_check_result_id BIGINT,
    resolved_by_check_result_id BIGINT,
    latest_check_result_id BIGINT,
    status VARCHAR(20),
    opened_at TIMESTAMP WITH TIME ZONE,
    last_checked_at TIMESTAMP WITH TIME ZONE,
    acknowledged_at TIMESTAMP WITH TIME ZONE,
    resolved_at TIMESTAMP WITH TIME ZONE,
    opening_reason VARCHAR(255),
    resolution_reason VARCHAR(255),
    CONSTRAINT fk_incident_monitor FOREIGN KEY (monitor_id) REFERENCES monitor(id),
    CONSTRAINT fk_incident_opened_by_check_result FOREIGN KEY (opened_by_check_result_id) REFERENCES check_result(id),
    CONSTRAINT fk_incident_resolved_by_check_result FOREIGN KEY (resolved_by_check_result_id) REFERENCES check_result(id),
    CONSTRAINT fk_incident_latest_check_result FOREIGN KEY (latest_check_result_id) REFERENCES check_result(id)
);

CREATE INDEX idx_monitor_owner_id ON monitor(owner_id);
CREATE INDEX idx_check_result_monitor_checked_at ON check_result(monitor_id, checked_at);
CREATE INDEX idx_incident_monitor_status ON incident(monitor_id, status);
