CREATE TABLE alert_channel (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    owner_id BIGINT,
    type VARCHAR(30) NOT NULL,
    destination VARCHAR(255) NOT NULL,
    enabled BOOLEAN NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE,
    updated_at TIMESTAMP WITH TIME ZONE,
    CONSTRAINT fk_alert_channel_owner FOREIGN KEY (owner_id) REFERENCES user_identity(id)
);

CREATE INDEX idx_alert_channel_owner_id ON alert_channel(owner_id);
CREATE INDEX idx_alert_channel_owner_enabled ON alert_channel(owner_id, enabled);
